module.exports = {
    owner: process.env.owner,
    token: process.env.token,
    prefix: process.env.prefix,
    dbHost: process.env.dbHost,
    dbName: process.env.dbName,
    dbUsername: process.env.dbUsername,
    dbPassword: process.env.dbPassword,
    log: process.env.log,
    apiToken: process.env.apiToken,
    permissions: process.env.permissions,
    webhookID: process.env.webhookID,
    webhookToken: process.env.webhookToken,
    backup: process.env.backup,
    color: parseInt(process.env.embedColor),
    fKey: process.env.fKey,
    clientId: process.env.clientId,
    deploy: process.env.deploy,
    controlsId: process.env.controlsId,
    corsAllow: process.env.corsAllow
}
