module.exports = {
    owner: process.env.owner,
    token: process.env.token,
    prefix: process.env.prefix,
    dbHost: process.env.dbHost,
    dbName: process.env.dbName,
    dbUsername: process.env.dbUsername,
    dbPassword: process.env.dbPassword,
    log: process.env.log,
    apiToken: process.env.apiToken,
    permissions: process.env.permissions,
    webhookID: process.env.webhookID,
    webhookToken: process.env.webhookToken,
    backup: process.env.backup,
    color: process.env.embedColor,
}
