name: Deploy Prod

on: [push]

jobs:
    deploy-production:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Deploying to production server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: |
                      export NVM_DIR=~/.nvm
                      source ~/.nvm/nvm.sh
                      cd kami-bot
                      rm package-lock.json
                      git pull
                      npm install
                      npx prisma generate
                      npm run build
                      pm2 restart kami-bot
